backend/urls.py
from django.urls import path
from backend.views.viewsMain import *
from backend.views.viewsUser import *
from backend.views.viewsQuiz import *
from backend.views.viewsTeacher import *

urlpatterns = [

    path('quiz/<slug:slug>/edit/', editQuiz, name='quizEdit'),
    path('question/<slug:slug>/add/', QuestionAnswerCreate.as_view(), name='questionAdd'),
    path('questions/<int:pk>/', QuestionAnswerUpdate.as_view(), name='questionUpdate'),
    path('question/<int:pk>/', QuestionDelete.as_view(), name='questionDelete'),

    path('', index, name='homeView'),
    path('course/', CourseListView.as_view(), name='courseList'),
    path('course/add/', addCourse, name='addCourse'),
    path('course/subscribe/', CourseListSubscribeView.as_view(), name='courseListSubscribe'),
    path('course/<slug:slug>/', CourseDetailView.as_view(), name='courseDetail'),
    path('course/<slug:slug>/edit', editCourse, name='editCourse'),
    path('course/<slug:slug>/delete', deleteCourse, name='deleteCourse'),
    path('course/<slug:slug>/subscribe', courseSubscribe, name='courseSubscribe'),
    path('course/<slug:slug>/unsubscribe', courseUnSubscribe, name='courseUnSubscribe'),

    path('section/<slug:slug>/edit/', editSection, name='sectionEdit'),
    path('section/<slug:slug>/delete/', deleteSection, name='sectionDelete'),
    path('section/<slug:slug>/add/', addSection, name='sectionAdd'),

    path('article/<slug:slug>/', ArticleDetailView.as_view(), name='articleDetail'),
    path('article/<slug:slug>/add/', addArticle, name='addArticle'),
    path('article/<slug:slug>/edit/', editArticle, name='editArticle'),
    path('article/<slug:slug>/delete/', deleteArticle, name='deleteArticle'),

    path('task/<slug:slug>/add/', addAssignment, name='addAssignment'),
    path('task/<slug:slug>/edit/', editAssignment, name='editAssignment'),
    path('task/<slug:slug>/delete/', deleteAssignment, name='deleteAssignment'),
    path('task/<slug:slug>/', AssignmentDetailView.as_view(), name='taskDetail'),

    path('quiz/<slug:slug>/', quizView, name='quizDetail'),  # quizDetailView
    path('quiz/<slug:slug>/create/', createQuiz, name='createQuiz'),
    path('quiz/<slug:slug>/start/', QuizDetailView.as_view(), name='quizDetailView'),
    path('quiz/<slug:slug>/data/', quizDataView, name='quizDataDetail'),  # quizDataDetail
    path('quiz/<slug:slug>/save/', saveQuizView, name='saveQuizView'),

    path('teacher_course/', courseAssignmentView.as_view(), name='courseAssignmentView'),
    path('upload_task/<slug:slug>/', UploadAssignmentView.as_view(), name='UploadAnswerTaskView'),
    path('upload_tasks/<slug:slug>/', resultAssignmentList, name='resultUploadList'),

    path('profile/', profile, name='profile'),
    path('login/', loginStudent, name='loginStudent'),
    path('register/', registerStudent, name='registerStudent'),
    path('logout/', logoutStudent, name='logoutStudent'),
    path('profile/<slug:slug>/', StudentDetailView.as_view(), name='studentDetail'),

]

remote_learning_diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('backend.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from slugify import unique_slugify
from itertools import chain
from operator import attrgetter
from django.core.validators import FileExtensionValidator
import random

# Create your models here.
class Group_custom(models.Model):
    name = models.CharField(max_length=10, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return f'{self.name}'


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=50, blank=True)
    lastName = models.CharField(max_length=50, blank=True)
    middleName = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    profilePicture = models.ImageField(null=True, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    about = models.CharField(max_length=250, blank=True)
    telegram_link = models.CharField(max_length=100, blank=True)
    group = models.ForeignKey(Group_custom, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return f'Teacher: {self.firstName} {self.lastName}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((unique_slugify(self.firstName), unique_slugify(self.lastName)))
        super(Teacher, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('studentDetail', kwargs={'slug': self.slug})

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    firstName = models.CharField(max_length=50, blank=True)
    lastName = models.CharField(max_length=50, blank=True)
    middleName = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    profilePicture = models.ImageField(null=True,blank=True)
    phone = models.CharField(max_length=50, blank=True)
    about = models.CharField(max_length=250, blank=True)
    telegram_link = models.CharField(max_length=100, blank=True)
    group = models.ForeignKey(Group_custom, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return f'Student: {self.firstName} {self.lastName} Group: '

    def get_absolute_url(self):
        return reverse('studentDetail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((unique_slugify(self.firstName), unique_slugify(self.lastName)))
        super(Student, self).save(*args, **kwargs)


class Course(models.Model):
    teachers = models.ManyToManyField(Teacher, blank=True)
    students = models.ManyToManyField(Student, blank=True)
    coursePicture = models.ImageField(null=True,blank=True)
    title = models.CharField(max_length=250, blank=False)
    description = models.TextField(blank=True)
    draft = models.BooleanField(default=True)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self.title)
        super(Course, self).save(*args, **kwargs)

    def __str__(self):
        teachers = ' '.join([f'Teacher {x.firstName} {x.lastName}' for x in self.teachers.all()])
        return f'Course: {self.title} Created: {teachers}'

    def get_absolute_url(self):
        return reverse('courseDetail', kwargs={'slug': self.slug})


class Section(models.Model):
    title = models.CharField(max_length=250, blank=True)
    description = models.TextField(blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    slug = models.SlugField()

    def return_all_task(self):
        list_item = sorted(chain(self.assignment_set.all(), self.article_set.all(), self.quiz_set.all()),
                           key=attrgetter('createdAt'))
        return list_item

    def return_mark_task(self):
        list_item = sorted(chain(self.assignment_set.all(), self.quiz_set.all()),
                           key=attrgetter('createdAt'))
        return list_item

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self.title)
        super(Section, self).save(*args, **kwargs)

    def __str__(self):
        return f'Section: {self.title} Course: {self.course.title}'


class Grade(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    amountPoint = models.FloatField(default=0)


class Quiz(models.Model):
    title = models.CharField(max_length=250, blank=True)
    point = models.IntegerField(blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    createdAt = models.DateTimeField(auto_now_add=True)
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    draft = models.BooleanField(default=True)


    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        self.slug = unique_slugify(self.title)
        super(Quiz, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('quizDetailView', kwargs={'slug': self.slug})

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'


class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"


class ResultQuiz(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    score = models.FloatField()

    def __str__(self):
        return f'Quiz: {self.quiz}, student - {self.student.firstName}'

    # def quizPassed(self, request):
    #     if ResultQuiz.objects.get(quiz=self.quiz, student=request.user.student):
    #         return True
    #     else:
    #         return False

class Article(models.Model):
    title = models.CharField(max_length=250, blank=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    description = models.TextField(default='')
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('articleDetail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title}'


class Assignment(models.Model):
    title = models.CharField(max_length=250, blank=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    description = models.TextField(default='')
    slug = models.SlugField(blank=True)
    pdf_task = models.FileField(upload_to='foo/',
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self.title)
        super(Assignment, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('taskDetail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title}'


class UploadAssignment(models.Model):
    answer = models.ForeignKey(Assignment, on_delete=models.CASCADE, blank=True)
    studentUpload = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(default='', blank=True)
    pdf_answer = models.FileField(upload_to='pdfAnswer/',
                                  validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    slug = models.SlugField(blank=True,null=True)
    rated = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('UploadAnswerTaskView', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((unique_slugify(self.studentUpload.firstName), unique_slugify(self.answer.title)))
        super(UploadAssignment, self).save(*args, **kwargs)

    def __str__(self):
        return f'UploadAnswerTask: {self.answer.title}, student - {self.studentUpload.firstName}'


class ResultAssignment(models.Model):
    task = models.OneToOneField(UploadAssignment, on_delete=models.CASCADE)
    comment = models.TextField(blank=True,null=True)
    score = models.FloatField(default=0)

    def __str__(self):
        return f'Quiz: {self.task}, student - {self.task.studentUpload.firstName}'

templates/screen/addArticle.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% if request.user.teacher %}
        <div class="col col-lg-2">

        </div>
        <div class="col col-lg-9">
        <h3>Add a new article: </h3>
        <form class="col-md-6" style="margin: auto" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button class="btn-sm btn-primary" type="submit">Add</button>

        </form>
    {% else %}
        <h1>You not allow to use this page!</h1>
    {% endif %}
</div>
{% endblock %}

templates/screen/addSection.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-md-center">
        <div class="col col-lg-3">

        </div>
        <div class="col col-lg-9">
            {% if request.user.teacher in course.teachers.all %}
                <h3>Add a new section to the course `{{ course.title }}`: </h3>
                <form class="col-md-6" style="margin: auto" method="post">
                    {% csrf_token %}

                    {{ form|crispy }}
                    <button class="btn-sm btn-primary" type="submit">Add</button>

                </form>
            {% else %}
                <h1>You not allow to use this page!</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/screen/assignmentDetailView.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if request.user.teacher in object.section.course.teachers.all %}
        <div style="margin: 0 0 0 80%">
            <a href="{% url 'editAssignment' object.slug %}">
                <button class="btn-sm btn-danger">Edit Assignment</button>
            </a>
            <a onclick="return confirm('Are you sure you want to delete this assignment?');" href="{% url 'deleteAssignment' object.slug %}">
                <button class="btn-sm btn-danger">Delete Assignment</button>
            </a>
        </div>
    {% endif %}
    Title: {{ object.title }}
    <hr>
    Section: {{ object.section.title }}
    <hr>
    Description: {{ object.description }}
    <hr>
    Pdf: <a class="btn-sm btn-primary" href="{{ object.pdf_task.url }}" target="_blank">Task</a>
    {% if not answered %}
        <h2>Submit answer</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}

                {% if not field.html_name == "answer" and not field.html_name == "studentUpload" %}

                    {{ field|as_crispy_field }}

                {% else %}
                    <div hidden>
                        {{ field }}
                    </div>
                {% endif %}


            {% endfor %}

            <button type="submit" class="btn-sm btn-primary">Submit answer</button>
        </form>

    {% else %}
        <h2> U already answered on this task</h2>
        <a href="{{ answered.pdf_answer.url }}" target="_blank">Your answer</a>
    {% endif %}



{% endblock %}

templates/screen/courseAssignment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block scripts %}
    <style>
        .accordion {
            background-color: #eee;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
        }

        .active, .accordion:hover {
            background-color: #ccc;
        }

        .panel {
            padding: 0 18px;
            display: none;
            background-color: white;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block content %}

    {% for course in course_list %}
        <button class="accordion"><h3 style="color: #1b2021">Assignment:</h3> {{ course.title }}</button>
        <div class="panel">


            {% for section in course.section_set.all %}
                <h4 style="color: #1b2021">Section: {{ section.title }}</h4>
                {% for assig in section.assignment_set.all %}
                    <a href="{% url 'resultUploadList' assig.slug %}"><h5 style="color: #1b2021">{{ assig }}</h5></a>
                {% endfor %}

            {% endfor %}


        </div>
    {% endfor %}

    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>
{% endblock %}

templates/screen/courseDetailView.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        /* Style The Dropdown Button */
        .dropbtn {
            background-color: #1b2021;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        /* The container <div> - needed to position the dropdown content */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Dropdown Content (Hidden by Default) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        /* Links inside the dropdown */
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        /* Change color of dropdown links on hover */
        .dropdown-content a:hover {
            background-color: #f1f1f1
        }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Change the background color of the dropdown button when the dropdown content is shown */
        .dropdown:hover .dropbtn {
            background-color: #1b2021;
        }
    </style>
    <div>
        {% if request.user.teacher in object.teachers.all %}
            <div style="margin: 0 0 0 90%">
                <a href="{% url 'editCourse' object.slug %}">
                    <button class="btn-sm btn-danger">Edit Course</button>
                </a>
            </div>
        {% endif %}
        {% for section in object.section_set.all %}
            <div class="dropdown">
                <button class="dropbtn">{{ section.title }}</button>
                <div class="dropdown-content">

                    {% for item in section.return_all_task %}
                        <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                    {% endfor %}

                    {% if request.user.teacher in object.teachers.all %}
                        <a href="{% url 'sectionEdit' section.slug %}">
                            <button class="btn-sm btn-danger" style="margin: 5px">Edit Section</button>
                        </a>
                    {% endif %}
                </div>

            </div>
        {% endfor %}
        {% if request.user.teacher in object.teachers.all %}
            <div class="dropdown">
                <a href="{% url 'sectionAdd' object.slug %}">
                    <button class="dropbtn">Add section</button>
                </a>
            </div>
        {% endif %}
        {#        {{ object.teachers.all }}#}
        {#        {% if request.user.teacher %}#}
        {#            <div class="dropdown">#}
        {#                <button class="dropbtn">Add section</button>#}
        {#            </div>#}
        {#        {% endif %}#}


    </div>
    <h2 style="margin: 20px">Rating</h2>
    <div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Group</th>
                <th scope="col">Rating</th>
            </tr>
            </thead>
            <tbody>
            {% for id,elem in mainList %}
                <tr>
                    <th scope="row">{{ id }}</th>
                    <td>{{ elem.0.firstName }} {{ elem.0.lastName }}</td>
                    <td>{{ elem.0.group }}</td>
                    <td>{{ elem.1.amountPoint }}</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>
{% endblock %}

templates/screen/courseListView.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <form class="form-inline" style="margin: 0 0 0 60%;padding: 20px" method="GET">
        {{ filter.form|crispy }}
        <button class="btn-sm" style="margin: 25px 0 0 0" type="submit">Search</button>
    </form>
    <div class="container">
        {% if request.user.teacher %}
            <div class="card"><a href="{% url 'addCourse' %}">
                <svg style="max-width: 30%; max-height: 30%;margin:100px 70px 0 100px"
                     xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                </svg>
                <h3 style="margin: 0 0 0 70px">Add course</h3>
            </a>
            </div>
        {% endif %}
        {% for course in filter.qs %}
            <a href="{{ course.get_absolute_url }}">{% include 'components/cardCourse.html' %}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/screen/editArticle.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if request.user.teacher in object.section.course.teachers.all %}
        <div class="col-md-2">
        </div>
        <form class="col-md-6" style="margin: auto" method="post">

            {% csrf_token %}
            <h3>Article: {{ object.title }}</h3>

            {{ form.media }}
            {{ form|crispy }}
            <button class="btn-sm btn-primary" type="submit">Update</button>
            <a onclick="return confirm('Are you sure you want to delete?');" style="{display: contents;}"
               class="btn-sm btn-danger"
               href=" ">Delete</a>

        </form>


    {% else %}
        <h1>You not allow to use this page!</h1>
    {% endif %}
{% endblock %}

templates/screen/editCourse.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% if request.user.teacher in course.teachers.all %}
        <div class="col-md-2">
        </div>
        <form class="col-md-6" style="margin: auto" method="post" enctype="multipart/form-data">>
            {% csrf_token %}
            <h3>Course: {{ course.title }}</h3>

            {{ form|crispy }}
            <button class="btn-sm btn-primary" type="submit">Update</button>
            <a onclick="return confirm('Are you sure you want to delete this course?');" style="{display: contents;}"
               class="btn-sm btn-danger"
               href="{% url 'deleteCourse' course.slug %} ">Delete</a>

        </form>


    {% else %}
        <h1>You not allow to use this page!</h1>
    {% endif %}
{% endblock %}

templates/screen/editSection.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if request.user.teacher in object.course.teachers.all %}
        <div class="col-md-2">
        </div>
        <form class="col-md-6" style="margin: auto" method="post">
            <button class="btn-sm btn-primary"><a href="{% url 'addArticle' object.slug %}">Add article</a></button>
            <button class="btn-sm btn-primary"><a href="{% url 'createQuiz' object.slug %}">Add quiz</a></button>
            <button class="btn-sm btn-primary"><a href="{% url 'addAssignment' object.slug %}">Add assignment</a></button>
            {% csrf_token %}
            <h3>Section: {{ object.title }}</h3>

            {{ form|crispy }}
            <button class="btn-sm btn-primary" type="submit">Update</button>
            <a onclick="return confirm('Are you sure you want to delete this section?');" style="{display: contents;}"
               class="btn-sm btn-danger"
               href="{% url 'sectionDelete' object.slug %} ">Delete</a>

        </form>


    {% else %}
        <h1>You not allow to use this page!</h1>
    {% endif %}
{% endblock %}

templates/screen/resultAssignmentList.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Rated</th>
                <th scope="col">Link</th>
            </tr>
            </thead>
            <tbody>
            {% for object in uploadAssignmentSet %}
                <tr>
                    <th scope="row">{{ object.0 }}</th>
                    <td>{{ object.1.studentUpload.firstName }} {{ object.1.studentUpload.lastName }}</td>
                    <td>{{ object.1.resultassignment.score }}</td>
                    <td><a href="{{ object.1.get_absolute_url }}" target="_blank">Review work</a></td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

{% endblock %}

templates/screen/reviewUploadTask.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Rated</th>
                <th scope="col">Link</th>
            </tr>
            </thead>
            <tbody>
            {% for object in uploadAnswerTaskSet %}
                <tr>
                    <th scope="row">1</th>
                    <td>{{ object.studentUpload.firstName }} {{ object.studentUpload.lastName }}</td>
                    <td>{{ object.resultuploadanswertask.score }}</td>
                    <td><a href="{{ object.get_absolute_url }}" target="_blank">Review work</a></td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

{% endblock %}

templates/screen/taskUploadDetailView.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    Title: {{ object.title }}
    <hr>
    Section: {{ object.section.title }}
    <hr>
    Description: {{ object.description }}
    <hr>
    Pdf: <a href="{{ object.pdf_task.url }}" target="_blank">Task</a>
    {% if not answered %}
        <h2>Submit answer</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}

                {% if not field.html_name == "answer" and not field.html_name == "studentUpload" %}

                    {{ field|as_crispy_field }}

                {% else %}
                    <div hidden>
                        {{ field }}
                    </div>
                {% endif %}


            {% endfor %}

            <button type="submit" class="btn btn-primary">Submit answer</button>
        </form>

    {% else %}
        <h2> U already answered on this task</h2>
        <a href="{{ answered.pdf_answer.url }}" target="_blank">Your answer</a>
    {% endif %}



{% endblock %}